version: 2
jobs:
  terraform:
    docker:
      - image: hashicorp/terraform
        environment:
          AWS_DEFAULT_REGION: us-east-1
    steps:
      - checkout
      - run:
          name: devsecops-ebs-backup - Set up Terraform
          command: cd terraform/test && terraform init -backend=false
      - run:
          name: devsecops-ebs-backup - Validate Terraform
          command: cd terraform/test && terraform validate -check-variables=false

workflows:
  version: 2

  validate:
    jobs:
      - terraform
